module.exports = {
    COMMUNITY_CHAT:"COMMUNITY_CHAT",
    USER_CONNECTED:"USER_CONNECTED",
    USER_RECIEVED:"USER_RECIEVED",
    MESSAGE_RECIEVED:"MESSAGE_RECIEVED",
    MESSAGE_SENT:"MESSAGE_SENT",
    MESSAGE_SEEN:"MESSAGE_SEEN",
    TYPING:"TYPING",
    VERIFY_USER:"VERIFY_USER",
    LOGOUT:"LOGOUT",
    SINGIN:"SINGIN",
}